language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true
scripts:
   - cargo build --verbose --workspace
   - cargo test --verbose --workspace
