[package]
name = "img_print"
version = "0.1.0"
authors = ["joe dao <joedao55@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
clap = "2.33.0"
